---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-lakeflow-io-v1alpha1-lakeflow
  failurePolicy: Fail
  name: vlakeflow.kb.io
  rules:
  - apiGroups:
    - lakeflow.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - lakeflows
  sideEffects: None
