# This rule is not used by the project lakeflow-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over lakeflow.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: lakeflow-controller
    app.kubernetes.io/managed-by: kustomize
  name: lakeflow-admin-role
rules:
- apiGroups:
  - lakeflow.io
  resources:
  - lakeflows
  verbs:
  - '*'
- apiGroups:
  - lakeflow.io
  resources:
  - lakeflows/status
  verbs:
  - get
