//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockStorage) DeepCopyInto(out *BlockStorage) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockStorage.
func (in *BlockStorage) DeepCopy() *BlockStorage {
	if in == nil {
		return nil
	}
	out := new(BlockStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommandExecutorSpec) DeepCopyInto(out *CommandExecutorSpec) {
	*out = *in
	if in.ScriptFileMode != nil {
		in, out := &in.ScriptFileMode, &out.ScriptFileMode
		*out = new(ScriptFileMode)
		(*in).DeepCopyInto(*out)
	}
	if in.InlineMode != nil {
		in, out := &in.InlineMode, &out.InlineMode
		*out = new(InlineMode)
		(*in).DeepCopyInto(*out)
	}
	if in.PythonProjectMode != nil {
		in, out := &in.PythonProjectMode, &out.PythonProjectMode
		*out = new(PythonProjectMode)
		(*in).DeepCopyInto(*out)
	}
	if in.ObjectStorage != nil {
		in, out := &in.ObjectStorage, &out.ObjectStorage
		*out = new(ObjectStorage)
		(*in).DeepCopyInto(*out)
	}
	if in.BlockStorage != nil {
		in, out := &in.BlockStorage, &out.BlockStorage
		*out = new(BlockStorage)
		(*in).DeepCopyInto(*out)
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]v1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]v1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.CredentialsRef != nil {
		in, out := &in.CredentialsRef, &out.CredentialsRef
		*out = new(v1.SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommandExecutorSpec.
func (in *CommandExecutorSpec) DeepCopy() *CommandExecutorSpec {
	if in == nil {
		return nil
	}
	out := new(CommandExecutorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependTrigger) DeepCopyInto(out *DependTrigger) {
	*out = *in
	if in.Workflows != nil {
		in, out := &in.Workflows, &out.Workflows
		*out = make([]Upstream, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependTrigger.
func (in *DependTrigger) DeepCopy() *DependTrigger {
	if in == nil {
		return nil
	}
	out := new(DependTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveMetastoreHikariCP) DeepCopyInto(out *HiveMetastoreHikariCP) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveMetastoreHikariCP.
func (in *HiveMetastoreHikariCP) DeepCopy() *HiveMetastoreHikariCP {
	if in == nil {
		return nil
	}
	out := new(HiveMetastoreHikariCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveMetastoreSpec) DeepCopyInto(out *HiveMetastoreSpec) {
	*out = *in
	if in.ConnectionParams != nil {
		in, out := &in.ConnectionParams, &out.ConnectionParams
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CredentialsRef != nil {
		in, out := &in.CredentialsRef, &out.CredentialsRef
		*out = new(v1.SecretReference)
		**out = **in
	}
	if in.HikariCP != nil {
		in, out := &in.HikariCP, &out.HikariCP
		*out = new(HiveMetastoreHikariCP)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveMetastoreSpec.
func (in *HiveMetastoreSpec) DeepCopy() *HiveMetastoreSpec {
	if in == nil {
		return nil
	}
	out := new(HiveMetastoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InlineMode) DeepCopyInto(out *InlineMode) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InlineMode.
func (in *InlineMode) DeepCopy() *InlineMode {
	if in == nil {
		return nil
	}
	out := new(InlineMode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFlow) DeepCopyInto(out *LakeFlow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFlow.
func (in *LakeFlow) DeepCopy() *LakeFlow {
	if in == nil {
		return nil
	}
	out := new(LakeFlow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LakeFlow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFlowCondition) DeepCopyInto(out *LakeFlowCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFlowCondition.
func (in *LakeFlowCondition) DeepCopy() *LakeFlowCondition {
	if in == nil {
		return nil
	}
	out := new(LakeFlowCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFlowFinishedTime) DeepCopyInto(out *LakeFlowFinishedTime) {
	*out = *in
	in.FinishedAt.DeepCopyInto(&out.FinishedAt)
	in.LastFinishedTime.DeepCopyInto(&out.LastFinishedTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFlowFinishedTime.
func (in *LakeFlowFinishedTime) DeepCopy() *LakeFlowFinishedTime {
	if in == nil {
		return nil
	}
	out := new(LakeFlowFinishedTime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFlowList) DeepCopyInto(out *LakeFlowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LakeFlow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFlowList.
func (in *LakeFlowList) DeepCopy() *LakeFlowList {
	if in == nil {
		return nil
	}
	out := new(LakeFlowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LakeFlowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFlowSpec) DeepCopyInto(out *LakeFlowSpec) {
	*out = *in
	if in.PodGC != nil {
		in, out := &in.PodGC, &out.PodGC
		*out = new(PodGCStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.TTLStrategy != nil {
		in, out := &in.TTLStrategy, &out.TTLStrategy
		*out = new(LakeFlowTTLStrategy)
		**out = **in
	}
	in.WorkflowTrigger.DeepCopyInto(&out.WorkflowTrigger)
	if in.Tasks != nil {
		in, out := &in.Tasks, &out.Tasks
		*out = make([]Task, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFlowSpec.
func (in *LakeFlowSpec) DeepCopy() *LakeFlowSpec {
	if in == nil {
		return nil
	}
	out := new(LakeFlowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFlowStatus) DeepCopyInto(out *LakeFlowStatus) {
	*out = *in
	if in.RetryStatus != nil {
		in, out := &in.RetryStatus, &out.RetryStatus
		*out = new(WorkflowRetryStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]LakeFlowCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FinishedTime != nil {
		in, out := &in.FinishedTime, &out.FinishedTime
		*out = new(LakeFlowFinishedTime)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFlowStatus.
func (in *LakeFlowStatus) DeepCopy() *LakeFlowStatus {
	if in == nil {
		return nil
	}
	out := new(LakeFlowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFlowTTLStrategy) DeepCopyInto(out *LakeFlowTTLStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFlowTTLStrategy.
func (in *LakeFlowTTLStrategy) DeepCopy() *LakeFlowTTLStrategy {
	if in == nil {
		return nil
	}
	out := new(LakeFlowTTLStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorage) DeepCopyInto(out *ObjectStorage) {
	*out = *in
	if in.MountSpec != nil {
		in, out := &in.MountSpec, &out.MountSpec
		*out = new(ObjectStorageMount)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorage.
func (in *ObjectStorage) DeepCopy() *ObjectStorage {
	if in == nil {
		return nil
	}
	out := new(ObjectStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageMount) DeepCopyInto(out *ObjectStorageMount) {
	*out = *in
	out.StorageSize = in.StorageSize.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorageMount.
func (in *ObjectStorageMount) DeepCopy() *ObjectStorageMount {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageMount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGCStrategy) DeepCopyInto(out *PodGCStrategy) {
	*out = *in
	if in.DeleteDelayDuration != nil {
		in, out := &in.DeleteDelayDuration, &out.DeleteDelayDuration
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGCStrategy.
func (in *PodGCStrategy) DeepCopy() *PodGCStrategy {
	if in == nil {
		return nil
	}
	out := new(PodGCStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PythonProjectMode) DeepCopyInto(out *PythonProjectMode) {
	*out = *in
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PythonProjectMode.
func (in *PythonProjectMode) DeepCopy() *PythonProjectMode {
	if in == nil {
		return nil
	}
	out := new(PythonProjectMode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleTrigger) DeepCopyInto(out *ScheduleTrigger) {
	*out = *in
	if in.StopStrategy != nil {
		in, out := &in.StopStrategy, &out.StopStrategy
		*out = new(StopStrategy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleTrigger.
func (in *ScheduleTrigger) DeepCopy() *ScheduleTrigger {
	if in == nil {
		return nil
	}
	out := new(ScheduleTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScriptFileMode) DeepCopyInto(out *ScriptFileMode) {
	*out = *in
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScriptFileMode.
func (in *ScriptFileMode) DeepCopy() *ScriptFileMode {
	if in == nil {
		return nil
	}
	out := new(ScriptFileMode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SparkExecutorSpec) DeepCopyInto(out *SparkExecutorSpec) {
	*out = *in
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PyFiles != nil {
		in, out := &in.PyFiles, &out.PyFiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.DriverResource.DeepCopyInto(&out.DriverResource)
	in.ExecutorResource.DeepCopyInto(&out.ExecutorResource)
	if in.CredentialsRef != nil {
		in, out := &in.CredentialsRef, &out.CredentialsRef
		*out = new(v1.SecretReference)
		**out = **in
	}
	if in.SparkConfig != nil {
		in, out := &in.SparkConfig, &out.SparkConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.UDFJars != nil {
		in, out := &in.UDFJars, &out.UDFJars
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraJars != nil {
		in, out := &in.ExtraJars, &out.ExtraJars
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HiveMetastoreSpec != nil {
		in, out := &in.HiveMetastoreSpec, &out.HiveMetastoreSpec
		*out = new(HiveMetastoreSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ObjectStorage != nil {
		in, out := &in.ObjectStorage, &out.ObjectStorage
		*out = new(ObjectStorage)
		(*in).DeepCopyInto(*out)
	}
	if in.BlockStorage != nil {
		in, out := &in.BlockStorage, &out.BlockStorage
		*out = new(BlockStorage)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SparkExecutorSpec.
func (in *SparkExecutorSpec) DeepCopy() *SparkExecutorSpec {
	if in == nil {
		return nil
	}
	out := new(SparkExecutorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SparkResource) DeepCopyInto(out *SparkResource) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SparkResource.
func (in *SparkResource) DeepCopy() *SparkResource {
	if in == nil {
		return nil
	}
	out := new(SparkResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StopStrategy) DeepCopyInto(out *StopStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StopStrategy.
func (in *StopStrategy) DeepCopy() *StopStrategy {
	if in == nil {
		return nil
	}
	out := new(StopStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Task) DeepCopyInto(out *Task) {
	*out = *in
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RetryPolicy != nil {
		in, out := &in.RetryPolicy, &out.RetryPolicy
		*out = new(TaskRetryPolicy)
		**out = **in
	}
	in.TaskSpec.DeepCopyInto(&out.TaskSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Task.
func (in *Task) DeepCopy() *Task {
	if in == nil {
		return nil
	}
	out := new(Task)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskPodSchedulingSpec) DeepCopyInto(out *TaskPodSchedulingSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]v1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskPodSchedulingSpec.
func (in *TaskPodSchedulingSpec) DeepCopy() *TaskPodSchedulingSpec {
	if in == nil {
		return nil
	}
	out := new(TaskPodSchedulingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskRetryPolicy) DeepCopyInto(out *TaskRetryPolicy) {
	*out = *in
	out.BackOff = in.BackOff
	out.MaxDuration = in.MaxDuration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskRetryPolicy.
func (in *TaskRetryPolicy) DeepCopy() *TaskRetryPolicy {
	if in == nil {
		return nil
	}
	out := new(TaskRetryPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskSpec) DeepCopyInto(out *TaskSpec) {
	*out = *in
	if in.PodScheduling != nil {
		in, out := &in.PodScheduling, &out.PodScheduling
		*out = new(TaskPodSchedulingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SparkExecutorSpec != nil {
		in, out := &in.SparkExecutorSpec, &out.SparkExecutorSpec
		*out = new(SparkExecutorSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CommandExecutorSpec != nil {
		in, out := &in.CommandExecutorSpec, &out.CommandExecutorSpec
		*out = new(CommandExecutorSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskSpec.
func (in *TaskSpec) DeepCopy() *TaskSpec {
	if in == nil {
		return nil
	}
	out := new(TaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Trigger) DeepCopyInto(out *Trigger) {
	*out = *in
	in.Depend.DeepCopyInto(&out.Depend)
	in.Schedule.DeepCopyInto(&out.Schedule)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Trigger.
func (in *Trigger) DeepCopy() *Trigger {
	if in == nil {
		return nil
	}
	out := new(Trigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Upstream) DeepCopyInto(out *Upstream) {
	*out = *in
	out.MinOffset = in.MinOffset
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Upstream.
func (in *Upstream) DeepCopy() *Upstream {
	if in == nil {
		return nil
	}
	out := new(Upstream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowRetryStatus) DeepCopyInto(out *WorkflowRetryStatus) {
	*out = *in
	if in.LastRetryTime != nil {
		in, out := &in.LastRetryTime, &out.LastRetryTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowRetryStatus.
func (in *WorkflowRetryStatus) DeepCopy() *WorkflowRetryStatus {
	if in == nil {
		return nil
	}
	out := new(WorkflowRetryStatus)
	in.DeepCopyInto(out)
	return out
}
